name: activate
description: 启动 — CPTSD 任务启动辅助工具
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
